# Generated by Django 6.0 on 2026-01-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="user/profile"),
        ),
        migrations.DeleteModel(
            name="ProfileImage",
        ),
    ]
