# Generated by Django 6.0 on 2026-01-08 22:35

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_pic_delete_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user/profile",
                validators=[users.validators.validate_file_size],
            ),
        ),
    ]
