# Generated by Django 6.0 on 2026-01-04 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_avg_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="avg_rating",
            field=models.FloatField(
                default=0,
                max_length=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
