# Generated by Django 6.0 on 2026-01-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_service_avg_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="avg_rating",
        ),
    ]
