# Generated by Django 6.0 on 2026-03-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_remove_service_avg_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["-id"]},
        ),
    ]
